name: GreenManAtlanta
favicon: null
layout_spectrum: 0
typography_spectrum: 0.61293
title: Green Man Atlanta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8b3ad'
    - '#141609'
    - '#4a4330'
    - '#b36300'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
